#on: [push]
on:
  push:
    branches:
    - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: katacoda validate:all
      run: |
        npm install -g katacoda-cli
        katacoda validate:all --repo=$GITHUB_WORKSPACE
    - name: markdown-link-check
      # https://stackoverflow.com/a/692407
      run: |
        set -x
        npm install -g markdown-link-check
        find . -name \*.md -exec markdown-link-check --quiet {} \; > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2)
        if [[ -s stderr.log ]]; then
          echo "stderr.log is not empty"
          cat stderr.log
          exit 113
        fi
